apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/isak0016/guestbook-backend:4f18377c5b02ef632934a754cf44bcefa4bad5f3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: guestbook-config
            - secretRef:
                name: guestbook-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
