apiVersion: v1
kind: Secret
metadata:
  name: gb-secret
stringData:
  DB_PASSWORD: hemlig
  REDIS_PASSWORD: hemlig
  POSTGRESQL_PASSWORD: hemlig
  POSTGRESQL_USER: guestbook
  POSTGRESQL_DATABASE: guestbook
